---
- block:
  - name: create prometheus group account
    ansible.builtin.group:
      name: prometheus
      system: yes
      state: present
  - name: create prometheus user account
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      system: yes
      shell: "/bin/false"
      state: present
  - name: fetch prometheus tar file and extract it to destination
    ansible.builtin.unarchive:
      src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
      dest: "/tmp"
      remote_src: yes
  - name: move prometheus package to final destination
    ansible.builtin.command:
      cmd: "mv /tmp/prometheus-{{ prometheus_version }}.linux-amd64 {{ prometheus_base_dir }}"
      creates: "{{ prometheus_base_dir }}"
  - name: setup file permissions
    ansible.builtin.file:
      path: "{{ prometheus_base_dir }}"
      state: directory
      recurse: yes
      owner: prometheus
      group: prometheus
      mode: "o-rwx"
  - name: install prometheus systemd service file
    ansible.builtin.template:
      src: "prometheus.service"
      dest: "/etc/systemd/system/prometheus.service"
      owner: root
      group: root
      mode: "0644"
  - name: setup prometheus systemd service
    ansible.builtin.systemd:
      name: "prometheus.service"
      daemon_reload: yes
      enabled: yes
      state: restarted
  tags:
    - prometheus
